### ISSUE TITLE
Define fork deployers update strategy

### ISSUE THREAD

**Issue by dianjuar** [angular-schule/ngx-deploy-starter#18]
Hello.

I think that is useful to have a guide to know how to update the new releases, features, bug fixes that are being released, to have them in our forks.

It would be nice to adopt a strategy that allows us to have our forks updated instead of making all the changes by hand, copying and pasting the new code. I think that rebase our changes to the master branch is a good strategy and will avoid the copy and paste.

--------

I have to update my fork to adopt the new releases I will go with the rebase strategy to set it down and document my experience here

**Comment by JohannesHoppe** [comment]
👍

**Comment by dianjuar** [comment]
The rebase strategy was a mess, no good experience doing it, a lot of conflicts, and definitely not something nice to do.

I already tried doing a cheery-pick of the changes that I wanted no implement on my fork and was easy, fun, and straightforward. 
I done it on implementing the [`--no-build`](https://github.com/bikecoders/ngx-deploy-npm/pull/31) option and was very easy. It even added @JohannesHoppe to the co-authors of the commit 😄

**Comment by JohannesHoppe** [comment]
I usually do such a job by comparing the folders 1:1 with a tool, eg. Beyond Compare.
Does that work for you?

For the future I will try to handle version bumps in a single PR, so that it is less work for you.
