### ISSUE TITLE
How to specify which project ? 

### ISSUE THREAD

**Issue by dianjuar** [angular-schule/ngx-deploy-starter#5]
Reading the [source code](https://github.com/angular-schule/ngx-deploy-starter/blob/master/src/ng-add.ts#L45) I saw that you can specify which project add the deployer, if don't, it takes the default project.

I tried with 

`ng add custom-deploy --project="my-project"`
`ng add custom-deploy --project=my-project`
`ng add custom-deploy project "my-project"`

Without success....

-------

Also the [ng add](https://angular.io/cli/add) documentation doesn't say anything about options

**Comment by JohannesHoppe** [comment]
The code was broken, see #9!
@dianjuar I would appreciate, if you could review this and double check what I have done laaaate at night! 😆
