### ISSUE TITLE
How to debug ?

### ISSUE THREAD

**Issue by dianjuar** [angular-schule/ngx-deploy-starter#6]
How to debug the deployer that you are building?

--------------------

I found a way but I don't feel confortable with that...

Put a `debugger` when you want your code stops and:
1. compile
2. link
3. install linked
4. And run `node --inspect  ./node_modules/@angular/cli/bin/ng deploy your-project`
5. Use your favorite debugger to debug

###### The steps 1-4 are in the [contributions steps](https://github.com/angular-schule/ngx-deploy-starter/blob/master/docs/README_contributors.md#2-npm-link)

**Comment by JohannesHoppe** [comment]
This is the only way I know how to test the code with a real project.
I adopted this approach from https://github.com/Azure/ng-deploy-azure/blob/master/CONTRIBUTING.md.

I am open to any improvement! 😃

**Comment by JohannesHoppe** [comment]
And YES!

It might be a good idea to document this properly. I have limited access to a computer right now. I would be happy about any help (e.g. a PR). 😉

**Comment by dianjuar** [comment]
Assign me the issue please: I would love to do it

**Comment by dianjuar** [comment]
I am planing to put this information in [docs/README_contributors.md](https://github.com/angular-schule/ngx-deploy-starter/blob/master/docs/README_contributors.md), I think is the right place to put this information instead of putting it on the readme

What do you think?

**Comment by JohannesHoppe** [comment]
Perfect place for that! 👍

**Comment by dianjuar** [comment]
I just come here to read step that I left because I forgot how to debug xD
