### ISSUE TITLE
Compiler with not general propose logic

### ISSUE THREAD

**Issue by dianjuar** [angular-schule/ngx-deploy-starter#8]
I found a piece of code in a general propose function that is probably attach to [angular-cli-ghpages](https://github.com/angular-schule/angular-cli-ghpages) 

https://github.com/angular-schule/ngx-deploy-starter/blob/aaf720adb4609a70c30de4a3b3772dd2cf1f84d4/src/deploy/actions.ts#L23-L27

You can see that says something about a `baseHref`

**Comment by JohannesHoppe** [comment]
You got me. 😅

Of course, I tried to keep the work low and took most of the code from angular-cli-ghpages. This switch is intended as an example of how you can apply other settings. See https://github.com/angular-schule/ngx-deploy-starter/blob/master/src/README.md#--base-href-
